import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    coverage: {
      provider: "v8",
      include: [
        "src/parser.ts",
        "src/mode.ts",
        "src/service.ts",
        "src/storage.ts",
        "src/browser-page-runner.ts",
        "src/browser-state-bridge.ts",
        "src/browser-state-main.ts",
        "src/browser-task-runner.ts",
        "src/browser-task-service.ts",
        "src/comment-loader.ts",
        "src/comment-runner.ts",
        "src/extension-credential.ts",
        "src/feed-detail-parser.ts",
        "src/feed-parser.ts",
        "src/interaction-runner.ts",
        "src/login-state.ts",
        "src/page-data.ts",
        "src/publication-assets.ts",
        "src/publication-runner.ts",
        "src/publication-service.ts",
        "src/publication-storage.ts",
        "src/publisher-dom.ts",
        "src/publisher-media.ts",
        "src/publisher-options.ts",
        "src/publisher-products.ts",
        "src/profile-parser.ts",
        "src/search-filters.ts",
      ],
      thresholds: {
        branches: 85,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
  },
});
